model: "transformer"
dataset: "dataset/data/test/RX0"
num_sensors: 2
epochs: 50
batch_size: 16
seq_len: 100
learning_rate: 0.021
optimizer: "sgd"
d_model: 128
embedding_size_src: 2
embedding_size_tgt: 1
num_heads: 8
dim_feedforward: 256
dropout: 0.115
num_encoder_layers: 1