model: "transformer"
dataset: "dataset/data/test-data/RX0"
num_sensors: 2
epochs: 1
batch_size: 16
seq_len: 12
learning_rate: 0.044
optimizer: 'sgd'
d_model: 128
embedding_size_src: 2
embedding_size_tgt: 1
num_heads: 1
dim_feedforward: 16
dropout: 0.178
num_encoder_layers: 5