model: "lstm"
dataset: "dataset/data/test/RX0"
num_sensors: 2
epochs: 100
learning_rate: 0.063
optimizer: "adam"
seq_len: 12
n_tgt_win: 3
batch_size: 64
dropout: 0.2
save_and_plot_period: 20
plot_number: 0
lr_scheduler_step_size: 50
lr_scheduler_gamma: 0.1
d_model: 128
