program: train.py
project: sensor-data-forecasting_lstm
method: bayes
metric:
  name: validation_loss
  goal: minimize
parameters:
  data_path:
    value: "dataset/data/chaos-bells-2/processed/RX0"
  num_sensors:
    value: 2
  epochs:
    value: 200
  batch_size:
    values: [16, 32, 64, 128, 256, 512]
  sequence_length:
    values: [16, 32, 64, 128, 256, 512, 1024]
  learning_rate:
    distribution: "uniform"
    min: 0.0001
    max: 0.1
  optimizer:
    values: ["adam", "sgd"]
