project: "sensor-data-forecasting-lstm"
program: train.py
method: bayes
metric:
  goal: minimize
  name: validation_loss
run_cap: 20
early_terminate:
  type: hyperband
  min_iter: 100
parameters:
  model:
    value: "lstm"
  dataset:
    value: "dataset/data/chaos-bells-4/processed/RX0"
  seq_len:
    value: 512
  n_tgt_win:
    value: 3
  num_sensors:
    value: 2
  batch_size:
    values: [16, 32, 64, 128, 256, 512]
  d_model:
    values: [16, 32, 64, 128, 256, 512]
  optimizer:
    values: ["sgd", "adam"]
  learning_rate:
    distribution: "uniform"
    min: 0
    max: 0.1
  epochs:
    value: 500
  save_and_plot_period:
    value: 20
  plot_number:
    value: 10
  dropout:
    distribution: "uniform"
    min: 0.1
    max: 0.3
  # lr_scheduler_step:
  #   values: [30, 40, 50, 80]
  # lr_scheduler_gamma:
  #   values: [0.1, 0.001, 0.0001]
