project: "sensor-data-forecasting-transformer"
program: train.py
method: random
metric:
  goal: minimize
  name: validation_loss
run_cap: 20
early_terminate:
  type: hyperband
  min_iter: 10
parameters:
  model:
    value: "transformer"
  dataset:
    value: "dataset/data/chaos-bells-2/processed/RX0"
  seq_len:
    values: [16, 32, 64, 128]
  num_sensors:
    value: 2
  embedding_size_src:
    value: 2
  embedding_size_tgt:
    value: 1
  batch_size:
    values: [16, 32, 64, 128, 256]
  d_model:
    values: [16, 32, 64, 128, 256]
  dim_feedforward:
    values: [16, 32, 64, 128, 256]
  dropout:
    distribution: "uniform"
    min: 0.1
    max: 0.3
  optimizer:
    values: ["sgd", "adam"]
  learning_rate:
    distribution: "uniform"
    min: 0
    max: 0.1
  n_heads:
    values: [1, 2, 4, 8, 16]
  num_encoder_layers:
    distribution: "int_uniform"
    min: 1
    max: 12
  epochs:
    value: 100
