model: "lstm"
dataset: "dataset/data/chaos-bells-3/processed/RX0"
num_sensors: 2
epochs: 1
learning_rate: 0.001
optimizer: "adam"
seq_len: 512
n_tgt_win: 3
batch_size: 32
input_size: 2
hidden_size: 2
d_model: 128
dropout: 0.2