model: "lstm"
dataset: "dataset/data/chaos-bells-4/processed/RX0"
num_sensors: 2
hidden_size: 32
epochs: 2
learning_rate: 0.001
optimizer: "adam"
seq_len: 10
n_tgt_win: 2
batch_size: 64
dropout: 0.2
save_and_plot_period: 1
plot_number: 10
