model: "lstm"
dataset: "dataset/data/chaos-bells-3/processed/RX0"
num_sensors: 2
epochs: 20
learning_rate: 0.001
optimizer: "adam"
seq_len: 512
n_tgt_win: 1
batch_size: 64
dropout: 0.2
save_and_plot_period: 1
plot_number: 10
