project: "sensor-data-forecasting-transformer"
model: "transformer"
data_path: "dataset/data/chaos-bells-2/processed/RX0"
num_sensors: 2
epochs: 1
batch_size: 32
sequence_length: 16
learning_rate: 0.001
optimizer: "adam"
model_params:
  embedding_size_src: 2
  embedding_size_tgt: 2
