model: "transformer"
dataset: "dataset/data/chaos-bells-3/processed/RX0"
num_sensors: 2
epochs: 1
batch_size: 32
seq_len: 512
n_tgt_win: 3
learning_rate: 0.001
optimizer: "adam"
embedding_size_src: 2
embedding_size_tgt: 1
save_and_plot_period: 1
plot_number: 10
