model: "lstm"
dataset: "dataset/data/chaos-bells-4/processed/RX0"
num_sensors: 2
hidden_size: 32
epochs: 500
learning_rate: 0.068
optimizer: "adam"
seq_len: 32
n_tgt_win: 3
batch_size: 32
dropout: 0.28
save_and_plot_period: 5
plot_number: 10