model: "lstm"
dataset: "dataset/data/chaos-bells-3/processed/RX0"
num_sensors: 2
epochs: 500
learning_rate: 0.063
optimizer: "adam"
seq_len: 512
n_tgt_win: 3
batch_size: 64
dropout: 0.2
save_and_plot_period: 5
plot_number: 10
lr_scheduler_step_size: 50
lr_scheduler_gamma: 0.1
