model: "lstm"
dataset: "dataset/data/chaos-bells-3/processed/RX0"
load_model_epoch: 1
load_model_path: "pelinski/sensor-data-forecasting-lstm/8duukmbh"
num_sensors: 2
epochs: 10
learning_rate: 0.042
optimizer: "adam"
seq_len: 512
n_tgt_win: 3
batch_size: 32
dropout: 0.2
save_and_plot_period: 1
plot_number: 5
