model: "lstm"
dataset: "dataset/data/chaos-bells-4/processed/RX0"
num_sensors: 2
epochs: 500
learning_rate: 0.068
optimizer: "adam"
seq_len: 512
n_tgt_win: 1
batch_size: 512
dropout: 0.28
save_and_plot_period: 10
plot_number: 10