# edited from https://github.com/lewiswolf/kac_drumset/blob/master/.github/workflows/tests.yml
name: Tests

on:
  push:
    branches: [main, dev]

jobs:
  all-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python: ["3.9"]

    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install OS specific dependencies - ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: pipenv run pip install torch --extra-index-url https://download.pytorch.org/whl/cu116

      - name: Install OS specific dependencies - macos
        if: ${{ matrix.os == 'macos-latest' }}
        run: pipenv run pip install torch; pipenv run pip install tensorflow

      - name: Install python dependencies
        run: pipenv install -d

      - name: Run unit tests
        run: pipenv run python test.py

      - name: Run training script
        run: pipenv run wandb disabled && pipenv run python train.py --config configs/github-test.yaml
