# edited from https://github.com/lewiswolf/kac_drumset/blob/master/.github/workflows/tests.yml
name: Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  all-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python: ["3.10"]

    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install python dependencies
        run: pipenv install -d

      - name: Run unit tests
        run: pipenv run python test.py